Controllers/CustomerController.cs
using CoreDepartmentProject.Core.Constants;
using CoreDepartmentProject.Models.Entites.Concrete;
using CoreDepartmentProject.Repositories.Abstract;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;


namespace CoreDepartmentProject.Controllers
{

	[Authorize]
	public class CustomerController : Controller
    {

        ICustomerRepository _customerRepository;
        public CustomerController(ICustomerRepository customerRepository)
        {
            _customerRepository = customerRepository;
        }
        public IActionResult Index()
        {
            var data = _customerRepository.GetAllDto();
            return View(data);
        }

        public IActionResult GetDetails(int Id)
        {
            var result = _customerRepository.GetDetailOfDto(Id);

            return View("detail", result);
        }

        [HttpGet]
        public IActionResult Add()
        {
            TempData["departments"] = _customerRepository.SelectOfDepartmentData();
            return View();
        }

        public IActionResult Add(Customer customer)
        {
            _customerRepository.Add(customer);
            return RedirectToAction("Index");
        }

        public IActionResult Delete(int id)
        {
            var result = _customerRepository.GetEntity(id).Data;
            _customerRepository.Delete(result);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Update(int Id)
        {
            var result = _customerRepository.GetEntity(Id).Data;
            if (result == null)
            {
                throw new Exception(Messages.GetDataErrorMessage);
            }

            ViewBag.Departments = _customerRepository.SelectOfDepartmentData();
            return View(result);
        }

        public IActionResult Update(Customer customer)
        {
            _customerRepository.Update(customer);
            return RedirectToAction("Index");
        }
    }
}

Controllers/DepartmentController.cs
using CoreDepartmentProject.Core.Constants;
using CoreDepartmentProject.Core.Constants.Results;
using CoreDepartmentProject.Core.Utilities.DataResults;
using CoreDepartmentProject.Models;
using CoreDepartmentProject.Models.Entites.Concrete;
using CoreDepartmentProject.Repositories.Abstract;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;

namespace CoreDepartmentProject.Controllers
{

	[Authorize]
	public class DepartmentController : Controller
    {
        public IDepartmentRepository _departmentRepository;
        public DepartmentController(IDepartmentRepository departmentRepository) => _departmentRepository = departmentRepository;

        public IActionResult Index()
        {
            var result = _departmentRepository.GetAll().Data ;
            return View(result);
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Add(Department department)
        {
            _departmentRepository.Add(department);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Update(int Id)
        {
            var result = _departmentRepository.GetEntity(Id).Data;
            if (result == null)
            {
                throw new Exception(Messages.GetDataErrorMessage);
            }
            return View(result);
        }
        [HttpPost]
        public IActionResult Update(Department department)
        {
            var result = _departmentRepository.Update(department).IsSuccess;
            return result == true
                ? RedirectToAction("Index")
                : Content("");


        }

        public IActionResult Delete(int Id)
        {
            var result = _departmentRepository.GetEntity(Id).Data;

            if (result == null)
            {
                throw new Exception(Messages.GetDataErrorMessage);
            }
            _departmentRepository.Delete(result);

            return RedirectToAction("Index");
        }

        public IActionResult GetDetail(int Id)
        {
            var result = (_departmentRepository.GetEntity(Id).Data , _departmentRepository.GetCustomersById(Id).Data);
            return View(result);
        }
    }
}

Views/Shared/_Layout.cshtml
<html>
<title>W3.CSS</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
<style>
    body
    {
        background-image: url('03016_strossmayer_3840x2400.jpg');
        background-repeat:no-repeat;
        background-size:cover;
        background-attachment:fixed;
        background-position: center;
    }

    }
</style>
<body>

    <!-- Sidebar -->
    <div class="w3-sidebar w3-light-grey w3-bar-block" style="width:10%">
        <h3 class="w3-bar-item">Menü</h3>
        <a href="@Url.Action("Index", "Department")" class="w3-bar-item w3-button">Departmanlar</a>
        <a href="@Url.Action("Index", "Customer")" class="w3-bar-item w3-button">Personeller</a>
        <a href="#" class="w3-bar-item w3-button">Hakkımızda</a>
        <a href="#" class="w3-bar-item w3-button">Çıkış</a>
    </div>

    <!-- Page Content -->
    <div>

        <div style="background-color:transparent; color:white; margin-left:2%;">       
            <h1 style="margin-left:10%; background-color:transparent;"> Personel Takip Uygulaması </h1>

        </div>

        <div class ="table">
            @RenderBody()
        </div>
        

    </div>
</body>
</html>